apiVersion: v1
kind: Service
metadata:
  name: {{ include "f1ap-proxy.fullname" . }}
  labels:
    {{- include "f1ap-proxy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
    - port: 38472
      targetPort: 38472
      protocol: SCTP
      name: f1c
  selector:
    {{- include "f1ap-proxy.selectorLabels" . | nindent 4 }}
